version: "3.8"

services:
  app:
    image: ghcr.io/adaptare01/sistema_ramar:latest
    container_name: ramar_app
    env_file:
      - .env.production
    environment:
      - PORT=3001
    networks:
      - proxy
      - adaptare
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: ramar_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
    restart: unless-stopped
    networks:
      - adaptare

networks:
  proxy:
    external: true
  adaptare:
    external: true
